version: "3.8"

services:
  
  snekbox:
    restart: unless-stopped
    container_name: snekbox
    image: ghcr.io/python-discord/snekbox:latest
    init: true
    ipc: none
    ports:
      - "127.0.0.1:8000:8060"
    privileged: true
    volumes:
      - user-base:/snekbox/user_base

  clodbot:
    build: .
    container_name: clodbot
    volumes:
      - type: bind
        source: ./data
        target: /app/data
    secrets:
      - discord_bot_secrets
    tty: true
    depends_on:
      - snekbox
 
volumes:
  user-base:

secrets:
  discord_bot_secrets:
    file: ./settings.json

